#!/usr/bin/env bash

check_factor()
{
    if [ $# -ne 3 ]; then
        args=("$@")
        num1=${args[-2]}
        num2=${args[-1]}
    else
        num1=$2
        num2=$3
    fi

    num=$(echo "$1" | tr ':' '=')

    echo "$num$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read i; do
        result=$(factor "$i")
        check_factor $result
    done < "$1"
fi
