#!/usr/bin/python3

import sys

def func():
    try:
        file_no = sys.argv[1]

        with open(file_no) as f:
            for factorial in f:
                factorial = int(factorial)
                if factorial % 2 == 0:
                    print("{}={}*{}".format(factorial, factorial // 2, 2))
                    continue
            i = 3
            while i < factorial // 2:
                if factorial % i == 0:
                    print("{}={}*{}".format(factorial, factorial // i, i))
                    break
            i = i + 2
            if i == (factorial // 2) + 1:
                print("{}={}*{}".format(factorial, factorial, i))
    except (IndexError):
            pass
func()
